blank_issues_enabled: false
contact_links:
  - name: "\U0001F4F1 iOS App related issues"
    url: "hhttps://github.com/cloudreve/ios-feedback/issues/new"
    about: Report issues related to the official iOS/iPadOS client.
  - name: "\U0001F5A5 Desktop client related issues"
    url: "https://github.com/cloudreve/desktop/issues/new"
    about: Report issues related to the official desktop client.
  - name: "\U0001F4AC Documentation Issues"
    url: "https://github.com/cloudreve/docs/issues/new"
    about: Report issues with the documentation, such as typos, outdated information, or missing content. Please provide the specific section and details of the issue.
  - name: "\U0001F4E7 Discussions"
    url: https://github.com/cloudreve/cloudreve/discussions
    about: General discussions and seek help from the community
